"""Add created and updated timestamps to oauth user identity model

Revision ID: 04bc165e7280
Revises: 179160532203
Create Date: 2021-08-02 02:57:53.891679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04bc165e7280'
down_revision = '179160532203'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oauthuseridentity', sa.Column('created', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.add_column('oauthuseridentity', sa.Column('updated', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('oauthuseridentity', 'updated')
    op.drop_column('oauthuseridentity', 'created')
    # ### end Alembic commands ###
