"""Add created and updated timestamps to user model

Revision ID: 179160532203
Revises: 70e84bb34da2
Create Date: 2021-08-02 02:54:30.079991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '179160532203'
down_revision = '70e84bb34da2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('created', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.add_column('user', sa.Column('updated', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'updated')
    op.drop_column('user', 'created')
    # ### end Alembic commands ###
