"""Rename column from username to external_user_id

Revision ID: 5911f815e616
Revises: 04bc165e7280
Create Date: 2021-08-07 03:58:55.108625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5911f815e616'
down_revision = '04bc165e7280'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oauthuseridentity', sa.Column('external_user_id', sa.String(), nullable=True))
    op.drop_constraint('_provider_username_uc', 'oauthuseridentity', type_='unique')
    op.create_unique_constraint('_provider_external_user_id_uc', 'oauthuseridentity', ['provider', 'external_user_id'])
    op.drop_column('oauthuseridentity', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oauthuseridentity', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint('_provider_external_user_id_uc', 'oauthuseridentity', type_='unique')
    op.create_unique_constraint('_provider_username_uc', 'oauthuseridentity', ['provider', 'username'])
    op.drop_column('oauthuseridentity', 'external_user_id')
    # ### end Alembic commands ###
