"""Renamed identity entity, changed unique constraint

Revision ID: 70e84bb34da2
Revises: cc87e2b68cb4
Create Date: 2021-08-02 02:41:12.384134

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '70e84bb34da2'
down_revision = 'cc87e2b68cb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauthuseridentity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', postgresql.ENUM('reddit', 'discord', 'twitter', 'ethereum', name='identityprovidername', create_type=False), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'username', name='_provider_username_uc')
    )
    op.create_index(op.f('ix_oauthuseridentity_id'), 'oauthuseridentity', ['id'], unique=False)
    op.drop_index('ix_useridentity_address', table_name='useridentity')
    op.drop_index('ix_useridentity_id', table_name='useridentity')
    op.drop_table('useridentity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('useridentity',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('provider', postgresql.ENUM('reddit', 'discord', 'twitter', 'ethereum', name='identityprovidername', create_type=False), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='useridentity_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='useridentity_pkey')
    )
    op.create_index('ix_useridentity_id', 'useridentity', ['id'], unique=False)
    op.create_index('ix_useridentity_address', 'useridentity', ['address'], unique=False)
    op.drop_index(op.f('ix_oauthuseridentity_id'), table_name='oauthuseridentity')
    op.drop_table('oauthuseridentity')
    # ### end Alembic commands ###
